### ISSUE TITLE
License Missing

### ISSUE THREAD

**Issue by nils-werner** [JorenSix/Pidato#1]
Your project is currently of little use to others trying to reuse the code [might be violating copyright](http://www.infoworld.com/article/2615869/open-source-software/github-needs-to-take-open-source-seriously.html):

> Code without an explicit license is protected by copyright and is by default All Rights Reserved. The person or people who wrote the code are protected as such. Any time you're using software you didn't write, licensing should be considered and abided.

Please add a license file to the repo to make clear what people may do or not do with your code.

**Comment by JorenSix** [comment]
Hi, 

Thanks for the feedback. It has been fixed. The code is licensed under the GPL. See the readme for details.
